### ISSUE TITLE
Convert issue (unrecognized option `-o' @ error/convert.c/ConvertImageCommand/2275)

### ISSUE THREAD

**Issue by tfrmb** [rumesh986/comicconvert#3]
Issue converting **any** cbr file in my collection fails on Ubuntu 16.04.2 LTS

Converting starts with extract messages that seems to work without an issue:

Extracting from x.rar
Extracting  .cbr/01 x1.jpg                           OK 

then it ends with the following error message: 
convert: unrecognized option `-o' @ error/convert.c/ConvertImageCommand/2275

Installed version of imagemagick from repo -> (8:6.8.9.9-7ubuntu5.7)

**Comment by rumesh986** [comment]
Just pushed an update to fix this issue. Let me know if you have any more problems

**Comment by tfrmb** [comment]
thanks - new version works fine
